version: '2'
services:
  debug:
    image: phpstorm/php-71-apache-xdebug
    ports:
     - "8081:80"
    volumes:
      - ./workshop/06_Debugging:/var/www/html
    environment:
        #change the line below with your IP address that is visible from Docker
        #See README for instruction about how to get the right IP address
        XDEBUG_CONFIG: remote_host=192.168.1.173
  mysql:
      image: phpstorm/mysql
      ports:
        - "33056:3306"
      volumes:
        - ./data:/var/lib/mysql